name: Python application test with Github Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python -m unittest dataPrep/test_data.py

  trigger_deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deploy to Docker Hub
          token: ${{ secrets.GITHUB_TOKEN }}